services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: evently
      POSTGRES_USER: evently
      POSTGRES_PASSWORD: evently123
      POSTGRES_ROOT_PASSWORD: rootpassword
    ports:
      - '5432:5432'
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db




