# Generated by Django 5.0.6 on 2024-06-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evently', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evently.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Rejected', 'Rejected')], default='Inactive', max_length=50),
        ),
    ]
