# Generated by Django 5.0.6 on 2024-06-16 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evently', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Music', 'Music'), ('Game', 'Game'), ('Education', 'Education'), ('Technology', 'Technology'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Science', 'Science')], max_length=100),
        ),
        migrations.AlterField(
            model_name='createusermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evently.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Inactive')], default=2, max_length=50),
        ),
    ]
