# Generated by Django 5.0.6 on 2024-06-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evently', '0002_alter_category_name_alter_createusermodel_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='evently.status'),
        ),
    ]
